//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Il2CppInterop.Runtime.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Il2CppInterop.Runtime.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8f8d8713,c3ec70
        ///380095f5,c3ece0
        ///1114b1a4,c3ecf0
        ///1adc136c,c3ee10
        ///f1bfc8ce,c3ef00
        ///15da43c0,c3f040
        ///978f06d,c3f050
        ///aee68645,f16e50
        ///96f8ee89,c3f0e0
        ///23463d36,c3f100
        ///c146ebe3,c3f2f0
        ///da71dfe8,c3f370
        ///b12a3331,c3f370
        ///e205a350,c3f560
        ///61ba0b2e,c3f610
        ///c2ac9c3d,c3f6f0
        ///9e9e1333,c3f710
        ///59c4b4e7,c3f730
        ///a1f927fb,c3f7b0
        ///8c18b60a,c3f7d0
        ///327349aa,c3f890
        ///6020b9db,c3f8b0
        ///f377976e,c3f8d0
        ///f222efd8,f17480
        ///36582bd9,c3f8f0
        ///683ccc7,c3fab0
        ///74d9d44c,c3fae0
        ///fba7c692,107a110
        ///b3f964e8,c3fb20
        ///337bfbb4,c3fba0
        ///be5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string icalltable {
            get {
                return ResourceManager.GetString("icalltable", resourceCulture);
            }
        }
    }
}
