[patch."https://github.com/RinLovesYou/dobby-sys.git"]
dobby-sys = { path = "../dobby-sys" }

[workspace]
members = [ "Bootstrap", "Proxy" ]

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"