[package]
name = "unity-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.37"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["libloaderapi"] }