name: .NET

on:
  push:
    branches: [ master ]
  create:
    tags:
     - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Extract Release Version
      id: get_version
      shell: bash
      run: |
        if [ "${GITHUB_REF#refs/tags/v}" != "$GITHUB_REF" ]; then
        echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
        else
        echo ::set-output name=version::${GITHUB_SHA}
        fi

    - name: Build
      run: ./build.sh --target=Pack --build_version=${{ steps.get_version.outputs.version }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./bin/zip/*.zip
        name: Il2CppInterop.${{ steps.get_version.outputs.version }}

    - name: Push to NuGet
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        dotnet nuget push -s ${{ secrets.BEPIN_DEV_NUGET_SOURCE }} -k ${{ secrets.BEPIN_DEV_NUGET_KEY }} ./bin/NuGet/*.nupkg

    - name: Publish a release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./bin/zip/*.zip
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
